import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { ProjectConfig } from "../config/projectConfig.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = path.resolve(__dirname, "../templates");

export async function generateExpressBase(config: ProjectConfig) {
  const projectPath = path.resolve(process.cwd(), config.projectName);
  const isTS = config.language === "ts";

  const folders = [
    "src/config",
    "src/controllers",
    "src/models",
    "src/routes",
    "src/middlewares",
    "src/utils",
    "src/services",
  ];

  for (const folder of folders) {
    await fs.mkdir(path.join(projectPath, folder), { recursive: true });
  }

  const packageJson: any = {
    name: config.projectName,
    version: "1.0.0",
    description: "Backend API generated by Muscle CLI",
    main: isTS ? "dist/server.js" : "src/server.js",
    type: "module",
    scripts: {
      start: isTS ? "node dist/server.js" : "node src/server.js",
      dev: isTS ? "tsx watch src/server.ts" : "node --watch src/server.js",
    },
    dependencies: {
      express: "^4.18.2",
      dotenv: "^16.3.1",
      cors: "^2.8.5",
      helmet: "^7.1.0",
      morgan: "^1.10.0",
    },
    devDependencies: {},
  };

  if (isTS) {
    packageJson.scripts.build = "tsc";
    packageJson.devDependencies = {
      typescript: "^5.3.3",
      "@types/express": "^4.17.21",
      "@types/node": "^20.10.5",
      "@types/cors": "^2.8.17",
      "@types/morgan": "^1.9.9",
      tsx: "^4.7.0",
    };

    const tsConfig = {
      compilerOptions: {
        target: "ESNext",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ["src/**/*"],
    };

    await fs.writeFile(
      path.join(projectPath, "tsconfig.json"),
      JSON.stringify(tsConfig, null, 2),
    );
  }

  if (config.database === "mongodb") {
    packageJson.dependencies["mongoose"] = "^8.0.0";
  }

  await fs.writeFile(
    path.join(projectPath, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );
}

export async function generateServerFiles(config: ProjectConfig) {
  const projectPath = path.resolve(process.cwd(), config.projectName);
  const srcPath = path.join(projectPath, "src");
  const isTS = config.language === "ts";
  const ext = isTS ? "ts" : "js";
  const templateExt = isTS ? "ts" : "js";

  // Read app template and inject project name
  const appTemplate = await fs.readFile(
    path.join(TEMPLATES_DIR, `framework/app.${templateExt}`),
    "utf-8",
  );
  const appCode = appTemplate.replace(/{{PROJECT_NAME}}/g, config.projectName);

  // Read server template and inject db import/connect lines
  const serverTemplate = await fs.readFile(
    path.join(TEMPLATES_DIR, `framework/server.${templateExt}`),
    "utf-8",
  );

  const dbImport =
    config.database !== "none"
      ? "import { connectDB } from './config/db.js';"
      : "";
  const dbConnect =
    config.database !== "none"
      ? "await connectDB();"
      : "// No database selected";

  const serverCode = serverTemplate
    .replace("{{DB_IMPORT}}", dbImport)
    .replace("{{DB_CONNECT}}", dbConnect);

  await fs.writeFile(path.join(srcPath, `app.${ext}`), appCode);
  await fs.writeFile(path.join(srcPath, `server.${ext}`), serverCode);

  let envContent = `PORT=3000\nNODE_ENV=development`;
  if (config.database === "mongodb") {
    envContent += `\nMONGO_URI=mongodb://localhost:27017/${config.projectName}`;
  }

  await fs.writeFile(path.join(projectPath, ".env"), envContent);
}
