import fs from "fs-extra";
import path from "path";
import { ProjectConfig } from "../config/projectConfig.js";

export async function generateExpressBase(config: ProjectConfig) {
    const projectPath = path.resolve(process.cwd(), config.projectName);
    const isTS = config.language === "ts";

    const folders = [
        "src/config",
        "src/controllers",
        "src/models",
        "src/routes",
        "src/middlewares",
        "src/utils",
        "src/services",
    ];

    for (const folder of folders) {
        await fs.ensureDir(path.join(projectPath, folder));
    }

    const packageJson: any = {
        name: config.projectName,
        version: "1.0.0",
        description: "Backend API generated by Muscle CLI",
        main: isTS ? "dist/server.js" : "src/server.js",
        type: "module",
        scripts: {
            start: isTS ? "node dist/server.js" : "node src/server.js",
            dev: isTS
                ? "tsx watch src/server.ts"
                : "node --watch src/server.js",
        },
        dependencies: {
            express: "^4.18.2",
            dotenv: "^16.3.1",
            cors: "^2.8.5",
            helmet: "^7.1.0",
            morgan: "^1.10.0",
        },
        devDependencies: {},
    };

    if (isTS) {
        packageJson.scripts.build = "tsc";
        packageJson.devDependencies = {
            typescript: "^5.3.3",
            "@types/express": "^4.17.21",
            "@types/node": "^20.10.5",
            "@types/cors": "^2.8.17",
            "@types/morgan": "^1.9.9",
            tsx: "^4.7.0",
        };

        const tsConfig = {
            compilerOptions: {
                target: "ESNext",
                module: "NodeNext",
                moduleResolution: "NodeNext",
                outDir: "./dist",
                rootDir: "./src",
                strict: true,
                esModuleInterop: true,
                skipLibCheck: true,
                forceConsistentCasingInFileNames: true,
            },
            include: ["src/**/*"],
        };
        await fs.writeJSON(path.join(projectPath, "tsconfig.json"), tsConfig, {
            spaces: 2,
        });
    }

    if (config.database === "mongodb") {
        packageJson.dependencies["mongoose"] = "^8.0.0";
    }

    await fs.writeJSON(path.join(projectPath, "package.json"), packageJson, {
        spaces: 2,
    });
}

export async function generateServerFiles(config: ProjectConfig) {
    const projectPath = path.resolve(process.cwd(), config.projectName);
    const srcPath = path.join(projectPath, "src");
    const isTS = config.language === "ts";
    const ext = isTS ? "ts" : "js";

    const appCode = `
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';

dotenv.config();

const app = express();

// Middlewares
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Health Check Route
app.get('/', (req, res) => {
    res.json({ 
        message: 'Welcome to ${config.projectName} API',
        status: 'Server is up and running'
    });
});

// 404 Handler
app.use((req, res) => {
    res.status(404).json({ error: 'Route not found' });
});

// Global Error Handler
app.use((err, req, res, next) => {
    console.error(err.stack);
    res.status(500).json({ error: 'Internal Server Error' });
});

export default app;
`.trim();

    const serverCode = `
import app from './app.js';
${config.database !== "none" ? "import { connectDB } from './config/db.js';" : ""}

const PORT = process.env.PORT || 3000;

const startServer = async () => {
    try {
        ${config.database !== "none" ? "await connectDB();" : "// No database selected"}
        
        app.listen(PORT, () => {
            console.log(\`🚀 Server is running on http://localhost:\${PORT}\`);
        });
    } catch (error) {
        console.error('❌ Failed to start server:', error);
        process.exit(1);
    }
};

startServer();
`.trim();

    await fs.writeFile(path.join(srcPath, `app.${ext}`), appCode);
    await fs.writeFile(path.join(srcPath, `server.${ext}`), serverCode);

    let envContent = `PORT=3000\nNODE_ENV=development`;
    if (config.database === "mongodb") {
        envContent += `\nMONGO_URI=mongodb://localhost:27017/${config.projectName}`;
    }

    await fs.writeFile(path.join(projectPath, ".env"), envContent);
}
